name: Build CHATGPT NOTE9PRO 

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    env:
      ARCH: arm64
      CROSS_COMPILE: aarch64-linux-gnu-
      LLVM: 1
      CC: clang

    steps:
    - name: Checkout kernel source
      uses: actions/checkout@v4
      with:
        repository: thofd/neko_kernel_xiaomi_gauguin
        fetch-depth: 0

    - name: Checkout SukiSU‑Ultra (susfs‑stable)
      run: |
        git clone --branch susfs-stable https://github.com/ShirkNeko/SukiSU-Ultra SukiSU-Ultra

    - name: 集成 SukiSU‑Ultra 与 SUSFS
      run: |
        curl -LSs https://raw.githubusercontent.com/ShirkNeko/SukiSU-Ultra/main/kernel/setup.sh | bash -s susfs-stable
      # 官方推荐直接使用 susfs-stable 分支，无需手动再集成 susfs :contentReference[oaicite:0]{index=0}

    - name: 安装编译依赖
      run: sudo apt-get update && sudo apt-get install -y build-essential bc bison flex libssl-dev libelf-dev libncurses-dev ccache

    - name: 下载并配置 AOSP Clang r416183b
      run: |
        mkdir -p toolchains
        cd toolchains
        curl -LSs https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/android12-clang-r416183b.tar.gz | tar xz
        cd ..
        # 将 clang 加入 PATH
        echo "$PWD/toolchains/clang-r416183b/bin" >> $GITHUB_PATH

    - name: 生成 defconfig
      run: make O=out vendor/gauguin_user_defconfig

    - name: 在 defconfig 中启用 SukiSU/SUSFS 所需选项
      run: |
        # GKI 2.0 内核需要打开 KPROBES 钩子 :contentReference[oaicite:1]{index=1}
        echo 'CONFIG_KPROBES=y'   >> out/.config
        # 启用 KernelSU 核心模块
        echo 'CONFIG_KSU=y'        >> out/.config
        # 非 GKI 2.0 设备需要手动钩子 :contentReference[oaicite:2]{index=2}
        echo 'CONFIG_KSU_MANUAL_HOOK=y' >> out/.config
        make -C . O=out olddefconfig

    - name: 编译内核 (IMAGE)
      run: make -C . O=out -j$(nproc)

    - name: 提取 Image
      run: cp out/arch/arm64/boot/Image .

    - name: 打包 AnyKernel3 ZIP
      run: |
        git clone https://github.com/anykernel/AnyKernel3 AnyKernel3
        cp Image AnyKernel3
        cd AnyKernel3
        zip -r ../gauguin-Image-AnyKernel3.zip .

    - name: 上传 ZIP 为 Artifact
      uses: actions/upload-artifact@v4
      with:
        name: gauguin-anykernel3-zip
        path: gauguin-Image-AnyKernel3.zip
